name: GGUF Loader
version: 1.0.0
description: >
  A Windows app for running Mistral, LLaMA, DeepSeek, and other GGUF models offline.
  No Python, no internet, no CLI — just drag-and-drop.
type: software
license: MIT
platform: Windows
website: https://ggufloader.github.io
repository: https://github.com/ggufloader/gguf-loader
author:
  name: Hussain Nazary
  email: hossainnazary475@gmail.com
  url: https://www.linkedin.com/in/hussain-nazary-188b4385
tags:
  - offline AI
  - LLM
  - GGUF
  - Windows
  - drag-and-drop
  - no Python
  - secure AI
models_supported:
  - Mistral
  - LLaMA 2
  - LLaMA 3
  - DeepSeek
  - Gemma
  - TinyLLaMA
