# _config.yml for GGUF Loader GitHub Pages
title: GGUF Loader
description: Run Mistral, LLaMA, DeepSeek, and other GGUF AI models offline on Windows — no Python, no internet, easy GUI.
url: "https://ggufloader.github.io"
baseurl: "/gguf-loader"

# Author info
author:
  name: Hussain Nazary
  email: hossainnazary475@gmail.com
  twitter_username: hussainnazary  # or ggufloader - be consistent
  github_username: hussainnazary2

# Social media
twitter:
  username: hussainnazary  # or ggufloader - match above

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Build settings
permalink: pretty
markdown: kramdown
lsi: false
incremental: false

# GitHub Pages settings
github:
  is_project_page: true

# Exclude files/folders from the site output
exclude:
  - README.md
  - LICENSE
  - node_modules
  - vendor
  - .gitignore
  - .git
