# Project Info
title: "GGUF Loader"
description: "Run Mistral, LLaMA, DeepSeek, and other GGUF AI models offline on Windows — no Python, no internet, easy GUI. GGUF Loader is the easiest privacy-first LLM runner for local deployment."
tagline: "Enterprise-Grade Local AI Deployment Platform"
lang: en
url: "https://ggufloader.github.io"
baseurl: "/gguf-loader"

# SEO Author Info 
author:
  name: "Hussain Nazary"
  email: "hossainnazary475@gmail.com"
  github: "hussainnazary2"
  twitter: "hussainnazary"
  linkedin: "https://linkedin.com/in/hussain-nazary-188b4385"

# Social Metadata
social:
  name: "GGUF Loader"
  links:
    - "https://github.com/hussainnazary2"
    - "https://github.com/ggufloader/gguf-loader"
    - "https://linkedin.com/in/hussain-nazary-188b4385"
    - "https://twitter.com/hussainnazary"

# GitHub Info
repository: "ggufloader/gguf-loader"
github:
  is_project_page: true

# Visual & SEO Assets
logo: "/docs/apple-touch-icon.png"
image: "/docs/apple-touch-icon.png"
theme_color: "#0a74da"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Build Behavior
permalink: pretty
markdown: kramdown
highlighter: rouge
safe: true
incremental: false
lsi: false

# Page Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
      author: "GGUF Loader"

# Time & Encoding
timezone: UTC
encoding: utf-8

# Sitemap Settings
sitemap:
  filename: sitemap.xml
  exclude:
    - /404.html

# Feed Settings
feed:
  collections:
    - posts
  excerpt_only: true

# File Inclusion & Exclusion
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules
  - vendor
  - .git
  - .github
  - .gitignore

include:
  - .htaccess
  - _pages
