# _config.yml for GGUF Loader GitHub Pages

title: GGUF Loader
description: Run Mistral, LLaMA, DeepSeek, and other GGUF AI models offline on Windows — no Python, no internet, easy GUI.
url: "https://ggufloader.github.io"    # Your GitHub Pages domain (without trailing slash)
baseurl: "/gguf-loader"                 # The repository name, adjust if different

# Author info
author:
  name: Hussain Nazary
  email: your-email@example.com
  twitter_username: hussainnazary
  github_username: hussainnazary2

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Permalinks
permalink: pretty

# Markdown processor
markdown: kramdown

# Exclude files/folders from the site output
exclude:
  - README.md
  - LICENSE
  - node_modules
  - vendor
  - .gitignore
  - .git

# Enable GitHub metadata
github:
  is_project_page: true

# SEO tag config (optional but recommended)
seo:
  name: GGUF Loader
  description: Run Mistral, LLaMA, DeepSeek, and other GGUF AI models offline on Windows — no Python, no internet, easy GUI.
  twitter:
    username: hussainnazary
  author:
    name: Hussain Nazary
  type: software

# Build settings
safe: true
lsi: false
incremental: false
